version: "3.9"

services:
  app:
    command: /bin/sh -c "chmod 777 /app/db.sqlite3"
    build:
      context: .
    restart: always
    environment:
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    volumes:
      - ./app:/app
  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - 80:8000
